### ISSUE TITLE
Variable type overflows into the following variable documentation

### ISSUE THREAD

**Issue by antonpup** [discosultan/vsdoc-2-md#1]
Sometimes when a function parameter type is too long, it will overflow into the documentation of the following parameter. And as a result, the type of the following parameter is lost.

![Example](http://puu.sh/qpq5f/b177acafd6.png)

```
        <member name="M:Aurora.Devices.ScriptedDevice.ScriptedDevice.UpdateDevice(System.Collections.Generic.Dictionary{Aurora.Devices.DeviceKeys,System.Drawing.Color},System.Boolean)">
            <summary>
            Updates the device with a specified color arrangement.
            </summary>
            <param name="keyColors">A dictionary of DeviceKeys their corresponding Colors</param>
            <param name="forced">A boolean value indicating whether or not to forcefully update this device</param>
            <returns></returns>
        </member>
```

**Comment by discosultan** [comment]
Thanks for reporting!

I pushed a commit that should fix the invalid splitting of method parameters (2df6694cf3d7ad9fbeda4ff023065e53c60522c6). 

Let me know if that did the trick.

**Comment by antonpup** [comment]
That seems to have done it! Thank you!
